apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: hsewalam/movie-service-image:latest #image de mon compte dockerhub
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: movie-service-persistent-storage
              mountPath: /app
      volumes:
        - name: movie-service-persistent-storage
          emptyDir: {}
