# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-service
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castService.image }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: cast-service-persistent-storage
              mountPath: /app
      volumes:
        - name: cast-service-persistent-storage
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  replicas: {{ .Values.movieService.replicas }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.movieService.image }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: movie-service-persistent-storage
              mountPath: /app
      volumes:
        - name: movie-service-persistent-storage
          emptyDir: {}
